version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nbfc-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - nbfc-network
        depends_on:
            - db
            - redis

    db:
        image: mysql:8.0
        container_name: nbfc-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - nbfc-network

    redis:
        image: redis:alpine
        container_name: nbfc-redis
        restart: unless-stopped
        networks:
            - nbfc-network

networks:
    nbfc-network:
        driver: bridge

volumes:
    dbdata:
