version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nbfc-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - nbfc-network
        ports:
            - "8080:80"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: nbfc-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - nbfc-network
        ports:
            - "3307:3306"

networks:
    nbfc-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
