version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nbfc-app
        restart: unless-stopped
        working_dir: /var/www/html
        ports:
            - "8000:8080"
        volumes:
            - ./:/var/www/html
        env_file:
            - .env
        networks:
            - nbfc-network
        depends_on:
            - db
            - redis

    db:
        image: mysql:8.0
        container_name: nbfc-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: nbfc
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: nbfc-user
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - nbfc-network

    redis:
        image: redis:alpine
        container_name: nbfc-redis
        restart: unless-stopped
        networks:
            - nbfc-network

networks:
    nbfc-network:
        driver: bridge

volumes:
    dbdata:
